spring.datasource.url=jdbc:sqlite:inventory_system.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

jwt.secret-key=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
# 1h in millisecond
jwt.expiration=3600000
auth.maxFailedAttempts=5
auth.lockTimeDurationMs=3600000
# auth.lockTimeDurationMs=2000

file.upload-dir=uploads/
